Cm 993 user b learn more climate impact card
ClimateMind/climatemind-frontend pull request #272
Opened 2022-04-09 19:55 UTC by johols

Showing details when clicking "Learn More" by fetching corresponding impact / solution card.

impacts:

![image](https://user-images.githubusercontent.com/10048951/162589651-8bced867-f1a8-4b86-9372-5cbd6c9e8a6e.png)

and solutions:

![image](https://user-images.githubusercontent.com/10048951/162589681-1f00fe94-a77b-4fa8-a0b3-84ab50832c3a.png)

2022-04-09 21:34 UTC, rodriguesk commented
@johols does the impact card overlay have the personal value tags at the bottom? I couldn’t tell from the image you attached. The designs in the story show the personal value tags at the bottom of the overlay for the impact cards.

2022-04-10 07:46 UTC, johols commented
> @johols does the impact card overlay have the personal value tags at the bottom? I couldn’t tell from the image you attached. The designs in the story show the personal value tags at the bottom of the overlay for the impact cards. So we want to ensure they are there too. I haven’t checked yet for your code in this PR.

2022-04-10 07:48 UTC, johols commented
@rodriguesk Yes, they are present according to the design:
![image](https://user-images.githubusercontent.com/10048951/162608141-e186d458-1625-4e38-89f3-04d7c82cd37a.png)

2022-04-10 15:36 UTC, rodriguesk commented
Awesome! Great work!

> On Apr 10, 2022, at 12:48 AM, johols ***@***.***> wrote:
> 
> ﻿
> External Email
> 
> @rodriguesk Yes, they are present according to the design:
> 
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-04-13 16:15 UTC, joaorpereira requested changes

2022-04-13 16:15 UTC, joaorpereira commented on src/pages/userB/SharedSolutions/SharedSolutions.tsx
> +      if(solutionIri) {
!!solutionIri && getSolutionDetails(solutionIri)

2022-04-13 16:15 UTC, joaorpereira commented on src/pages/userB/SharedSolutions/SharedSolutions.tsx
> +      if(solutionIds.length < 2 ) {
```
if( solutionIds.length < 2 || solutionIds.find(item => item.solutionId === currentSolutionId)) {
    return false
}
return true
```

2022-04-13 16:15 UTC, joaorpereira commented on src/pages/userB/SharedSolutions/SharedSolutions.tsx
> +      if(e.target.checked){ // add to selected solutions
```
e.target.checked ? 
setSolutionIds(prevIds => [...prevIds, {solutionId: solutionId}]) : 
setSolutionIds(solutionIds.filter(item => item.solutionId !== solutionId));
```

2022-04-18 14:00 UTC, joaorpereira approved these changes

2022-04-20 20:29 UTC, merged