Cm 879 delete conversation in conversation dashboard
ClimateMind/climatemind-frontend pull request #315
Opened 2022-08-07 15:08 UTC by nbrix

* created new DeleteIconButton component
* updated useConversation hook to include a deleteConversation mutation
* created API for deleting conversation
* updated cypress tests

2022-08-07 17:16 UTC, rodriguesk commented
@nbrix it looks like this code isn't passing the automated tests. Can you look into fixing the code so it passes them?

2022-08-07 17:19 UTC, rodriguesk commented
The pipeline should run automatically with each edit you do. If not then it might be because you email for your computer's gitconfig isn't matching the email for your github account. You can start the pipeline manually using app.circleci.com though. See the attached screenshot for how to do that  ![Screen Shot 2022-08-07 at 10 18 06 AM](https://user-images.githubusercontent.com/19840874/183303060-61241b4f-1b42-4507-9d39-52770eac87d0.png)

2022-08-07 23:52 UTC, rodriguesk commented
Once @Svenstar74 approves this then I can use admin rights to merge to develop, since it's a bug in github requiring percy to pass (we deleted it from the project). This bug should disappear for new branches made that don't have Percy involved to begin with.

2022-08-12 14:40 UTC, Svenstar74 requested changes

2022-08-12 14:40 UTC, Svenstar74 commented on src/api/deleteConversation.ts
> +  const HEADERS = { Authorization: jwt ? `Brearer ${jwt}` : '' };
_Brearer_ is a spelling mistake. It should be _Bearer_. That's an error we have four times in the code, while it's only written correctly twice. Should fix this in all occurences.

2022-08-12 14:40 UTC, Svenstar74 commented on src/api/deleteConversation.ts
> +  const CONVESATIONS_ENDPOINT = `/conversation/${conversationId}`;
Spelling mistake: 
wrong: CONVESATIONS_ENDPOINT
right: CONVERSATIONS_ENDPOINT

2022-08-12 14:40 UTC, Svenstar74 commented on src/components/ConversationsList.tsx
> +              If you do the link to this conversation will stop working.
Was a bit confused when reading the sentence in the UI.
Either add a comma: If you do, the link to this conversation will stop working.
Or rephrase it, eg.: Deleting the conversation will disable the link as well.

2022-08-12 14:40 UTC, Svenstar74 commented on src/hooks/useConversations.tsx
> +          message: error.response?.data?.error || 'Unknow Error has occoured',
Google says, that 'occoured' is actually spelled 'occurred'. That's something that exists in multiple places throughout the code, probably because of copy / pasting. Could fix this, as this is a message the user might see.

2022-08-12 15:57 UTC, nbrix commented on src/components/ConversationsList.tsx
> +              If you do the link to this conversation will stop working.
@rodriguesk I copied the message directly from adobe xd, but I can have it simply say "Are you sure you want to delete your conversation with **NAME**?" Or if you think I should be more explicit, I can then add "This action cannot be undone and will disable the link to this conversation."

So it would look something like this:
>#### Delete Conversation
>Are you sure you want to delete your conversation with **Nik**?

Or
>#### Delete Conversation
>Are you sure you want to delete your conversation with **Nik**? This action cannot be undone and will disable the link to this conversation.

2022-08-12 16:07 UTC, rodriguesk commented
You can ask Stephanie on the team or Natasha. I think option 1 is best for now. Less words is usually better.
> Are you sure you want to delete your conversation with Nik?
> 


> On Aug 12, 2022, at 8:57 AM, Nikolas Brix ***@***.***> wrote:
> 
> ﻿
> External Email
> 
> @nbrix commented on this pull request.
> 
> In src/components/ConversationsList.tsx:
> 
> > +        {isModalOpen && (
> +          <CMModal
> +            handleClose={handleModalClose}
> +            onConfirm={onConfirmDelete}
> +            isOpen={isModalOpen}
> +          >
> +            <Typography
> +              variant="body1"
> +              component="p"
> +              id="modal-title"
> +              className={classes.modalHeader}
> +            >
> +              Delete this conversation?
> +            </Typography>
> +            <Typography variant="body1" component="p" id="modal-description">
> +              If you do the link to this conversation will stop working.
> @rodriguesk I copied the message directly from adobe xd, but I can have it simply say "Are you sure you want to delete your conversation with NAME?" Or if you think I should be more explicit, I can then add "This action cannot be undone and will disable the link to this conversation."
> 
> So it would look something like this:
> 
> Delete Conversation
> 
> Are you sure you want to delete your conversation with Nik?
> 
> Or
> 
> Delete Conversation
> 
> Are you sure you want to delete your conversation with Nik? This action cannot be undone and will disable the link to this conversation.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-08-15 19:03 UTC, Svenstar74 approved these changes

2022-08-15 19:33 UTC, merged