CM-566: Reset ca reset his forgotten password (Part 1)
ClimateMind/climatemind-frontend pull request #319
Opened 2022-08-14 16:16 UTC by Svenstar74

We will split this ticket into two different PRs. This one will:
- Provide the user a button + dialog to reset his password
- Send the email to the user

The next PR then continues, when the user opens the link in the email to set his new password. We do this to better test the sendgrid email stuff (and the PR would probably become quite large and chaotic otherwise as well).

![image](https://user-images.githubusercontent.com/78958483/184545660-b9a4e2a6-4421-4f93-ac66-7ca036aa41ac.png)

2022-08-14 17:38 UTC, rodriguesk requested changes
Looks great (in terms of what the screens look like). I think the button used to submit the email should say "submit" instead of "confirm". @NickCallaghan will have to approve the rest of the story regarding tests, style, and actual code.

2022-08-16 05:58 UTC, rodriguesk approved these changes

2022-08-16 09:29 UTC, NickCallaghan commented on src/api/postPasswordResetLink.ts
> +      withCredentials: true,
are credentials needed? If the user has forgotten their password will they not be logged out?

2022-08-16 11:14 UTC, Svenstar74 commented on src/api/postPasswordResetLink.ts
> +      withCredentials: true,
Removed the withCredentials part

2022-08-17 22:41 UTC, NickCallaghan submitted a review, later dismissed
Looks great @Svenstar74 Thanks for adding the tests. Looks like there is a conflict to resolve but feel free to merge after that is solved.

2022-08-18 04:37 UTC, rodriguesk approved these changes
Awesome job!

2022-08-20 20:56 UTC, rodriguesk commented
@Svenstar74 anyhold up on merging this to develop? If it’s ready please merge it yourself :)

2022-08-20 21:48 UTC, merged