Added custom ScrollToTop hook
ClimateMind/climatemind-frontend pull request #373
Opened 2022-11-09 03:44 UTC by nbrix

* Added ScrollToTop hook

2022-11-13 16:20 UTC, Svenstar74 requested changes
While working on one of my tickets, I saw that eg. in 'ClimateFeed.tsx' there's a <ScrollToTopOnMount /> component.
I like that you put your <ScrollToTop /> component in the Router.tsx, so that we have that automatically on every page and so far I don't see an issue with that.
I'd just like to clean things a bit up, so could you take a look at the existing ScrolToTopOnMount component? Maybe you want to delete that and all of its occurences, so that we have only one.

2022-11-19 21:11 UTC, nbrix commented
> 

I ended up deleting all occurrences of ScrollToTopOnMount. I think it's a lot easier to maintain that way because if someone new joined they would have to know to add that on each page, which I didn't know.

2022-11-19 23:31 UTC, Svenstar74 approved these changes

2022-11-19 23:42 UTC, Svenstar74 approved these changes

2022-11-26 17:08 UTC, merged